[package]
name = "threads_in_impl"
version = "0.1.0"
authors = ["Tomasz Kostur <tomasz.kostur@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
